export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

export const GET_ALLDOCUMENTS_REQUEST = 'GET_ALLDOCUMENTS_REQUEST';
export const GET_ALLDOCUMENTS_SUCCESS = 'GET_ALLDOCUMENTS_SUCCESS';
